const {test}=require('node:test');const assert=require('node:assert/strict');
const {plan,validateBatch,mapResponse,run,redact}=require('../dist/nodes/CivicDataForge/core.js');
const input={operation:'quote',address:'400 S Orange Ave',city:'Orlando',state:'FL'};
const quote=()=>({statusCode:200,body:{schema_version:'civicdataforge.agent-quote.v1',input_contract_version:'civicdataforge.evidence-input.v2',task:'us_property_decision',quote_state:'READY',charged:false,quote_id:'cdfq_'+'a'.repeat(24),issued_at:new Date(Date.now()-1000).toISOString(),expires_at:new Date(Date.now()+600000).toISOString(),purchase:{store_url:'https://apify.com/civicdataforge/civicdataforge-evidence-gateway'}}});
const paid=()=>plan({...input,operation:'evidence',customerAuthorized:true,idempotencyKey:'logical-order-001'});
const packet=(decision='EVIDENCE_FOUND')=>({statusCode:200,body:{schema_version:'civicdataforge.evidence-api-response.v1',task:'us_property_decision',request_id:'cdf_req_fixture',decision,complete_for_bounded_scope:true,receipt_hash:'b'.repeat(64),evidence_packet:{source_url:'https://example.org/official',rows:[]}}});
test('free quote cannot select a paid destination',()=>{const p=plan(input);assert.equal(p.path,'/api/quote');assert.equal(p.idempotencyKey,undefined);assert.equal(p.body.retentionDays,0)});
test('quote returns scoped handoff only',()=>{const v=mapResponse(plan(input),quote());assert.equal(v.state,'scope_ready_not_evidence');assert.equal(v.paymentAttempted,false);assert.equal(v.evidenceRetrieved,false);assert.equal(v.handoff.automaticPurchase,false)});
for(const [name,change] of [['charge',b=>b.charged=true],['wrong task',b=>b.task='other'],['schema',b=>b.schema_version='other'],['expiry',b=>b.expires_at=new Date(0).toISOString()],['future clock',b=>b.issued_at=new Date(Date.now()+120000).toISOString()],['malicious purchase',b=>b.purchase.store_url='https://evil.example'],['quote ID',b=>b.quote_id='bad']])test('reject quote '+name,()=>{const r=quote();change(r.body);assert.throws(()=>mapResponse(plan(input),r))});
test('malformed JSON rejected',()=>assert.throws(()=>mapResponse(plan(input),{statusCode:200,body:'oops'}),/RESPONSE_NOT_JSON/));
test('usage needs no property scope',()=>assert.equal(plan({operation:'usage'}).path,'/api/v1/usage'));
for(const operation of ['buy','mcp',''])test('unknown operation '+operation,()=>assert.throws(()=>plan({...input,operation}),/UNKNOWN_OPERATION/));
for(const bad of [{address:'{{ $json.address }}'},{state:'Florida'},{city:''},{address:'32801'},{address:'400 S Orange\nAuthorization: bad'}])test('input bounds '+JSON.stringify(bad),()=>assert.throws(()=>plan({...input,...bad})));
test('explicit customer authority required',()=>assert.throws(()=>plan({...input,operation:'evidence',idempotencyKey:'logical-001'}),/CUSTOMER_AUTHORIZATION_REQUIRED/));
test('string authority is not boolean',()=>assert.throws(()=>plan({...input,operation:'evidence',customerAuthorized:'true',idempotencyKey:'logical-001'}),/CUSTOMER_AUTHORIZATION_REQUIRED/));
for(const key of ['short','a'.repeat(129),'x\r\nHeader: evil','with spaces'])test('invalid stable key '+key.slice(0,15),()=>assert.throws(()=>plan({...input,operation:'evidence',customerAuthorized:true,idempotencyKey:key})));
test('key and exact payload stable across retry planning',()=>assert.deepEqual(paid(),paid()));
test('batch rejects reused key with changed scope',()=>assert.throws(()=>validateBatch([paid(),plan({...input,address:'500 S Orange Ave',operation:'evidence',customerAuthorized:true,idempotencyKey:'logical-order-001'})]),/DIFFERENT_INPUT/));
test('identical replay batch accepted',()=>validateBatch([paid(),paid()]));
for(const status of [401,403,409,422,429,502,503])test('HTTP '+status+' cannot become no-match or leak body',()=>assert.throws(()=>mapResponse(paid(),{statusCode:status,body:{error:'SECRET_VALUE'}}),e=>!e.message.includes('SECRET_VALUE')));
for(const state of ['EVIDENCE_FOUND','NO_PUBLISHED_MATCH','REVIEW_REQUIRED','SOURCE_UNAVAILABLE','SCOPE_INCOMPLETE'])test('preserve evidence state '+state,()=>assert.equal(mapResponse(paid(),packet(state)).decision,state));
test('bad evidence receipt rejected',()=>{const r=packet();r.body.receipt_hash='x';assert.throws(()=>mapResponse(paid(),r),/INVALID_EVIDENCE_CONTRACT/)});
test('no transport retry/purchase fallthrough',async()=>{let calls=0;await assert.rejects(()=>run(paid(),async()=>{calls++;throw new Error('secret transport URL')}),/TRANSPORT_ERROR_OUTCOME_UNKNOWN/);assert.equal(calls,1)});
test('free quote only one transport call',async()=>{let calls=0;await run(plan(input),async p=>{calls++;assert.equal(p.path,'/api/quote');return quote()});assert.equal(calls,1)});
test('successful response credential redaction',async()=>{const r=packet();r.body.evidence_packet={apiKey:'private',note:'known-secret',headers:{Authorization:'Bearer token'}};const v=await run(paid(),async()=>r,'known-secret');const s=JSON.stringify(v);assert(!s.includes('known-secret'));assert(!s.includes('private'));assert(!s.includes('Bearer token'))});
test('usage schema validated and key prefix omitted',()=>{const v=mapResponse(plan({operation:'usage'}),{statusCode:200,body:{schema_version:'civicdataforge.api-usage.v1',access_state:'ACTIVE',key_prefix:'secret-prefix'}});assert.equal(v.usage.key_prefix,undefined)});
test('credential-bearing property names are removed',()=>assert.equal(JSON.stringify(redact({'known-secret':'x',nested:{'prefix-known-secret-tail':'x',okay:'v'}},'known-secret')),'{"nested":{"okay":"v"}}'));
test('receipt and subject verification not implied',()=>{const v=mapResponse(paid(),packet());assert.deepEqual(v.verification,{envelopeValidated:true,receiptCryptographicallyVerified:false,subjectIndependentlyBound:false})});
module.exports={input,quote,packet};
