const {test}=require('node:test');const assert=require('node:assert/strict');
const {CivicDataForge}=require('../dist/nodes/CivicDataForge/CivicDataForge.node.js');
const {CivicDataForgeApi}=require('../dist/credentials/CivicDataForgeApi.credentials.js');
const params={operation:'quote',address:'400 S Orange Ave',city:'Orlando',state:'FL'};
const q=()=>({statusCode:200,body:{schema_version:'civicdataforge.agent-quote.v1',input_contract_version:'civicdataforge.evidence-input.v2',task:'us_property_decision',quote_state:'READY',charged:false,quote_id:'cdfq_'+'a'.repeat(24),issued_at:new Date(Date.now()-1000).toISOString(),expires_at:new Date(Date.now()+600000).toISOString(),purchase:{store_url:'https://apify.com/civicdataforge/civicdataforge-evidence-gateway'}}});
function context(rows,handler=async()=>q(),authHandler=handler){const calls=[];let credentials=0;return {calls,get credentialReads(){return credentials},getInputData:()=>rows.map(()=>({json:{}})),getNodeParameter:(n,i)=>rows[i][n],getNode:()=>({name:'CDF',type:'civicDataForge',typeVersion:1,position:[0,0],parameters:{}}),getCredentials:async()=>{credentials++;return {apiKey:'cdf_test_'+'x'.repeat(40)}},continueOnFail:()=>false,helpers:{httpRequest:async o=>{calls.push({authenticated:false,o});return handler(o)},httpRequestWithAuthentication:async(name,o)=>{calls.push({authenticated:true,name,o});return authHandler(o)}}}}
test('node quote uses no credentials/auth and links each item',async()=>{const c=context([params,params]);const [out]=await CivicDataForge.prototype.execute.call(c);assert.deepEqual(out.map(x=>x.pairedItem),[{item:0},{item:1}]);assert.equal(c.credentialReads,0);assert(c.calls.every(x=>!x.authenticated&&x.o.disableFollowRedirect===true));assert.equal(c.calls.length,2)});
test('all batch validation occurs before any HTTP',async()=>{const c=context([params,{...params,address:''}]);await assert.rejects(()=>CivicDataForge.prototype.execute.call(c));assert.equal(c.calls.length,0)});
test('paid requires authority before credentials or HTTP',async()=>{const c=context([{...params,operation:'evidence',idempotencyKey:'order-001',customerAuthorized:false}]);await assert.rejects(()=>CivicDataForge.prototype.execute.call(c));assert.equal(c.calls.length,0);assert.equal(c.credentialReads,0)});
test('paid transport uses CDF credential and exact stable key',async()=>{const c=context([{...params,operation:'evidence',idempotencyKey:'order-001',customerAuthorized:true}],async()=>({statusCode:409,body:{error:'upstream secret'}}));c.getCredentials=async()=>({apiKey:'cdf_test_'+'x'.repeat(40),approvedEvidenceRequests:JSON.stringify([{address:params.address,city:params.city,state:params.state,idempotencyKey:'order-001',expiresAt:new Date(Date.now()+3600000).toISOString()}])});await assert.rejects(()=>CivicDataForge.prototype.execute.call(c),/IDEMPOTENCY_CONFLICT_OR_PENDING/);assert.equal(c.calls.length,1);assert.equal(c.calls[0].name,'civicDataForgeApi');assert.equal(c.calls[0].o.headers['Idempotency-Key'],'order-001');assert.equal(c.calls[0].o.url,'https://civicdataforge.pages.dev/api/v1/evidence')});
test('continue on fail returns safe linked error only',async()=>{const c=context([params],async()=>{throw new Error('private token')});c.continueOnFail=()=>true;const [out]=await CivicDataForge.prototype.execute.call(c);assert.deepEqual(out,[{json:{error:'TRANSPORT_ERROR_OUTCOME_UNKNOWN',outcome:'not_confirmed'},pairedItem:{item:0}}])});
test('credential test only reads usage',()=>{const c=new CivicDataForgeApi();assert.equal(c.test.request.url,'/api/v1/usage');assert.equal(c.test.request.method,'GET');assert.equal(c.properties[0].typeOptions.password,true)});
test('usage operation never runs evidence',async()=>{const c=context([{operation:'usage'}],async()=>({statusCode:200,body:{schema_version:'civicdataforge.api-usage.v1',access_state:'ACTIVE'}}));await CivicDataForge.prototype.execute.call(c);assert.equal(c.calls[0].o.method,'GET');assert.equal(c.calls[0].o.url,'https://civicdataforge.pages.dev/api/v1/usage')});
test('wrong credential type blocked before request',async()=>{const c=context([{operation:'usage'}]);c.getCredentials=async()=>({apiKey:'apify-wrong-token'});await assert.rejects(()=>CivicDataForge.prototype.execute.call(c),/VALID_CDF_CREDENTIAL_REQUIRED/);assert.equal(c.calls.length,0)});
test('credential test explicitly disables redirects',()=>assert.equal(new CivicDataForgeApi().test.request.disableFollowRedirect,true));
